markdown: kramdown
sass:
  style: :compressed
exclude:
  - README.md
  - wp-content/README.md
  - vendor
  - node_modules
permalink: /:categories/:year/:month/:day/

title: Austin JavaScript

description: >
  Austin JavaScript is a meetup group focused on JavaScript and the open web.

twitter:
  user: AustinJS
  url: https://twitter.com/AustinJS

people:
  organizers:
    lawnsea:
      twitter: lawnsea
      full: Lon Ingram
      short: Lon
      avi: https://pbs.twimg.com/profile_images/970161690233864192/rztEhZFR_400x400.jpg
    aaron:
      twitter: aaronj1335
      full: Aaron Stacy
      short: Aaron
      avi: https://pbs.twimg.com/profile_images/3281266042/5069b845017701c465760d25ba54b83c_400x400.jpeg
    drewml:
      twitter: drewml
      full: Andrew Levine
      short: Andrew
      avi: https://pbs.twimg.com/profile_images/950842904771284992/pZwj7Nim_400x400.jpg
  emeriti:
    joemccann:
      twitter: joemccann
      full: Joe McCann
      short: Joe
      avi: https://pbs.twimg.com/profile_images/846386052910637056/tWGT0XAz_400x400.jpg
    slexaxton:
      twitter: SlexAxton
      full: Alex Sexton
      short: Alex
      avi: https://pbs.twimg.com/profile_images/653393861453045760/6paq641-_400x400.jpg
    rebecca:
      twitter: rmurphey
      full: Rebecca Murphey
      short: Rebecca
      avi: https://pbs.twimg.com/profile_images/504070124509229056/6t-MUDgL_400x400.jpeg
